### ISSUE TITLE
Why are special names considered as public?

### ISSUE THREAD

**Issue by funkyfuture** [kalekundert/autoclasstoc#16]
i found it irritating that `is_public` considers "dunder" names as public. in my perception over the years the names that start and end with double underscores are a subset of private names.

for me that raised two practical issues: it took me a while to figure out that this was intended behaviour and not a bug. and y `predicate` implementations are a little longer. both is solvable, but especially the first point might be a showstopper for some users.

**Comment by kalekundert** [comment]
The reason why `is_public()` considers dunder names public is that most (all?) dunder *methods* are public.  If a class defines `__getitem__`, public users of that class can do `x[k]`.  If a class defines `__eq__` and `__hash__`, public users can put instances of the class in sets/dicts (as keys).  The same reasoning applies to `__iter__`, `__len__`, `__call__`, `__bool__`, etc. 
 Even methods like `__getstate__` and `__setstate__`, which aren't directly triggered by the user, still communicate that a class is publicly pickle-able.  And `__init__` is almost always an important part of the public interface.

At the same time, dunder *data attributes* are not public: `__dict__`, `__slots__`, `__doc__`, etc.  Right now, the code handles these two cases by considering all dunder names public, but considering dunder data attributes to not actually be data attributes.  In retrospect, it would probably make more sense for `is_public()` to only return true for "normal" names, and for `PublicMethods` sections to include `is_special() == True` methods as a special case.  That wouldn't change the default behavior of any of the sections, but would maybe make writing custom predicates a bit more intuitive.  I'd also be open to including a `StrictPublicMethods` section (not sure about the name) that excludes dunder methods, and to being more explicit in the docs about what's considered a public method.  Would any of these changes address your concerns?

**Comment by funkyfuture** [comment]
i can follow your argument, i'd still consider it differently though. these special methods are implementing a public interface, but they are not supposed to be accessed by the dunder names. and i (hence?) never came across api docs that describe these interfaces under the implementing names, but rather in the general docstring of a class.

anyway, this is all a matter of conventions and this tool should therefore allow any usage.

> In retrospect, it would probably make more sense for `is_public()` to only return true for "normal" names, and for `PublicMethods` sections to include `is_special() == True` methods as a special case.

yes, i think that is sufficient to avoid larger irritations.

i don't really see the need for an extra contributed configuration class as these are generally easy to define.

**Comment by ExtremOPS** [comment]
Hi, I think my question is fitting into this discussion perfectly 😅 

I is with `autoclasstoc==1.3.0` possible to do not show the dunder methods such as `__init__` (preferably a custom list of exclusion) in the `Public Methods` section?

<img width="400" alt="image" src="https://user-images.githubusercontent.com/25452149/156983354-01887da2-13b6-4eaa-822f-a34163e8e633.png">

**Comment by ExtremOPS** [comment]
A quick -- but only local fix -- is the definition of

```python
class PublicMethodsExclusive(PublicMethods):
    """
    Include a "Public Methods" section in the class TOC.
    """
    key = 'public-methods-exclusive'
    title = "Public Methods:"

    def predicate(self, name, attr, meta):
        return PublicMethods.predicate(name, attr, meta) and name[0] != '_'
```

inside [`sections.py`](https://github.com/kalekundert/autoclasstoc/blob/7faa8b5e23bc5eb66527a1887335adeb2a3a1d6a/autoclasstoc/sections.py#L218).

If that is of any interest I am happy to fork etc. it

**Comment by ExtremOPS** [comment]
To achieve it also for projects building on [www.readthedocs.org](www.readthedocs.org) or similar I added the following to my `conf.py`. Just in case somebody else is also interested.

```python
...
from autoclasstoc.sections import PublicMethods
...
class PublicMethodsExclusive(PublicMethods):
    """
    Include a "Public Methods" section in the class TOC.
    """
    key = 'public-methods-exclusive'
    title = 'Public Methods:'

    def predicate(self, name, attr, meta):
        out = PublicMethods.predicate(self, name, attr, meta)
        out = out and name[0] != '_'
        return out
...
autoclasstoc_sections = [
    ...
    'public-methods-exclusive',
    ...
]

**Comment by kalekundert** [comment]
If you want to make a PR, I'd be interested in a slightly more general version of the `Section` classes that accept a regular expression (or list of regular expressions) to exclude.  The implementation I'm thinking of would add an `exclude` attribute to the base `Section` class, so that all sections would gain the ability to exclude specific members:
```
import re
from more_itertools import always_iterable

class Section:
    exclude = None

    def predicate(self, name, attr, meta):
        if exclude:
            return any(
                re.match(p, name)
                for p in always_iterable(self.exclude)
            )
```
The various `Section` subclasses would have to be updated to call this method:
```
class PublicMethods(Sections):

    def predicate(self, name, attr, meta):
        return super().predicate() and is_method(name, attr) and is_public(name)
```
In fact, now that I think about it, I could probably also just do this myself.  Let me know if you want to make a PR, otherwise I'll try to get around to this over the weekend

**Comment by ExtremOPS** [comment]
I am happy to do it. But I understand the maybe unnecessary overhead of reviewing my code 😸 

Your repository, your 📞  call.

**Comment by ExtremOPS** [comment]
I'll do it now
