### ISSUE TITLE
Inherited from string is incorrect

### ISSUE THREAD

**Issue by johanseland** [kalekundert/autoclasstoc#20]
I am trying to use autoclasstoc for a large Python package containing several modules. 
When using autoclasstoc, the generated "Inherited from <class>" is not rendered correctly Rather than linking to the parent class, it displays the string "Inherited from    : py: class:`parent`

This seems to be caused by [make_inherited_details](https://github.com/kalekundert/autoclasstoc/blob/b75737451abcfd16a1cda2f3a02d8ba8a2ed43cd/autoclasstoc/utils.py#L126) introducing extra spaces when generating the text.

**Comment by kalekundert** [comment]
Good catch, it looks like I introduced this bug when I was trying to reformat the code.  This should be fixed by fc547f6, which is now available as v1.5.1.
