### ISSUE TITLE
Warnings about autosummary import cycle emitted when using Sphinx 7.4.0+

### ISSUE THREAD

**Issue by jwodder** [kalekundert/autoclasstoc#39]
When using v1.6.0 of autoclasstoc with Sphinx 7.4.0 or higher (including Sphinx 8.0.2, the current version), warnings of the following form are emitted despite the documented code not referring to the current module:

```
WARNING: Summarised items should not include the current module. Replace 'mypackage.Foo.__init__' with '__init__'. [autosummary.import_cycle]
```

This happens even with a project as simple as:

<details>
<summary><code>src/mypackage/__init__.py</code></summary>

```python
class Foo:
    def __init__(self, value: int) -> None:
        """Create a Foo"""
        self.value = value
```

</details>

<details>
<summary><code>docs/conf.py</code></summary>

```python
project = "mypackage"
author = "John T. Wodder II"
copyright = "2024 John T. Wodder II"  # noqa: A001

extensions = [
    "autoclasstoc",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
]

autodoc_default_options = {
    "members": True,
    "undoc-members": True,
}

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

exclude_patterns = ["_build"]
source_suffix = ".rst"
source_encoding = "utf-8"
master_doc = "index"
version = "0.0.0"
release = "0.0.0"
today_fmt = "%Y %b %d"
default_role = "py:obj"
pygments_style = "sphinx"

html_theme = "sphinx_rtd_theme"
html_theme_options = {
    "collapse_navigation": False,
    "prev_next_buttons_location": "both",
}
html_last_updated_fmt = "%Y %b %d"
html_show_sourcelink = True
html_show_sphinx = True
html_show_copyright = True
```

</details>

<details>
<summary><code>docs/index.rst</code></summary>

```rst
.. module:: mypackage

=========
mypackage
=========

.. autoclass:: Foo
    :special-members:
    :no-undoc-members:
    :exclude-members: __eq__, __hash__, __repr__, __weakref__

    .. autoclasstoc::
```

</details>

A full MVCE is available at https://github.com/jwodder/autoclass-warns-20241008.

**Comment by kalekundert** [comment]
Thanks for the bug report and MVCE!  It's been a while since I updated this package, so I'm not surprised that there are warnings with newer versions of sphinx.  I'll try to look into fixing them over the weekend.

**Comment by kalekundert** [comment]
Ok, this should be fixed now.  Briefly, the problem was that `autoclasstoc` used fully-qualified names whenever it made a cross-reference.  This used to work fine (and was easy to implement), but at some point `autosummary` started forbidding the use of fully-qualified names in cases where the module could be inferred from context.  TBH this seems like a bug in `autosummary` to me, but regardless I was able to work around it.

I'll push a new release to PyPI soon.
