### ISSUE TITLE
provide a new release?

### ISSUE THREAD

**Issue by funkyfuture** [kalekundert/autoclasstoc#7]
(to some regret) i'm using poetry and when i want to add `autoclasstoc` from this git repo it can't figure out this package's version. are you planning to do a new release soon? b/c installing from the cheeseshop makes things easier.

**Comment by kalekundert** [comment]
Thanks for the reminder.  I just made a new release (v1.1.0).  It should be up on PyPI now.

**Comment by funkyfuture** [comment]
cool.
